### ISSUE TITLE
Clearify the relation to Pellet

### ISSUE THREAD

**Issue by cknoll** [Galigator/openllet#53]
I discovered this repository because I had an [issue](https://github.com/stardog-union/pellet/issues/48) with https://github.com/stardog-union/pellet. In this [pull request](https://github.com/stardog-union/pellet/pull/32) the openllet repo is referenced. However, it remains unclear, whether openllet is a fork of pellet and might become its successor or in what other relation the repos stand.

Some more information in the README would help potential new users to have clear knowledge which of the two reasoners they should use for which use case.

**Comment by Galigator** [comment]
This is an very old [PR](https://github.com/stardog-union/pellet/pull/32) that have not reviewed. After a will I decided that pellet was inactive and not fit for my needs. So I fork it to correct some problems. When https://github.com/stardog-union/pellet become a showroom(by my opinion) for the commercial [StarDog](https://www.stardog.com/) product , the fork (openllet) have been separated. The dependence between the two remain for historical reason only.

Right now I am closing the [PR](https://github.com/stardog-union/pellet/pull/32) because it is very old.
Your issue isn't related to this [PR](https://github.com/stardog-union/pellet/pull/32) because it wasn't merged.
In your [issue](https://github.com/stardog-union/pellet/issues/48) you may have encounter a bug specific to version of java > 11.  With openllet, you may try 
`$ ./openllet.sh help`

I am also using java-14, in next release java >= 14 may become a requirement as I don't have the time to check older version (and love news features).

NB: I don't have time to search solutions for existing know-bug inside openllet.

**Comment by cknoll** [comment]
I understand the background. However, there are still some things unclear to me, e.g:
- Can I use `java -jar openllet.jar ...` as a drop in replacement for `java -jar pellet.jar ...`?
  - Background: pellet is shipped with the python project [owlready](owlready2.readthedocs.io/) which calls it as a subprocess.
 - What is meant with "migration" in the README.md? The migration from pellet to openllet?
 
 I would suggest a short section in the README.md like this:
 
 ```
 ## Historical Notes and Migration
Openllet (i.e. this project) has started as a fork of [pellet](https://github.com/stardog-union/pellet)
but evolved to be an independent project. The original repo seems to be inactive.
The following changes/improvement have been made:
 
- ...
- ...

To replace the dependency pellet by openllet cosider the folliwing:

- ...
- ...

 ```

**Comment by Galigator** [comment]
Well, there is no 'openllet.jar' so I guess that the answer to your first question is 'no'.
For your second question, I don't remember all small differences... sorry, but you are please to create a list.
