### ISSUE TITLE
cannot resolve import when installing with Maven

### ISSUE THREAD

**Issue by eroux** [Galigator/openllet#9]
When I import latest version:

```xml
<dependency>
    <groupId>com.github.galigator.openllet</groupId>
    <artifactId>openllet-jena</artifactId>
    <version>2.6.0</version>
</dependency>
```

and import it in a java file:

```java
import com.github.galigator.openllet;
```

I get the error:

```
[ERROR] xxx.java:[23,28] package com.github.galigator does not exist
```

**Comment by eroux** [comment]
Ok, I found that

```
import openllet.jena.PelletReasonerFactory;
```

was what I was looking for... please provide a small doc or at least one small example so that dumb people like me don't get too lost... Thank you!

**Comment by luciferz2012** [comment]
Hi, Eroux,

I'm also learning Openllet recently. You may refer to the examples here:

https://github.com/Galigator/openllet/tree/integration/examples/src/main/java/openllet/examples

**Comment by Galigator** [comment]
Thx you two for your efforts using this fork.

I have only put a warn in the the README.txt concerning this kind of change because I am using Eclipse and it does all the job for me. When I have problem with a import, Eclipse auto-magically resolve it when I save the file.
When I see a problem with import, my natural behaviour with Eclipse is to remove all imports and re-save the file.

Maybe, if yours tests are small enough we can put them in the examples section (and re-work the README.txt).

Plz continue to report your problems because there are many fatal bugs that need to be worked.
